// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jvppdhpcevipwwmlztxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2cHBkaHBjZXZpcHd3bWx6dHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MjE3NzksImV4cCI6MjA2Nzk5Nzc3OX0.IX_hUfUHAw1Fq-g14IbqYWc5yfsjjSoT77Cyuc2tle4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);